config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :pages

  get '*path', to: 'user_defined_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :uri, uniqueness: { case_sensitive: false }

  scope :all_in_menu, -> { where(in_menu: true) }
  scope :ordered_by_title, -> { order(title: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to pages_path, notice: 'Page successfully created!'
    else
      render :new
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to pages_path, notice: 'Page successfully saved!'
    else
      render :edit
    end
  end

  def destroy
    @page = Page.find(params[:id])

    if @page.destroy
      redirect_to pages_path, notice: 'Page successfully removed!'
    else
      render :edit
    end
  end

  private

  def page_params
    params.require(:page).permit(:title, :uri, :in_menu, :body)
  end
end

app/controllers/user_defined_page_controller.rb
class UserDefinedPageController < ApplicationController
  def index
    redirect_to_user_defined_page || raise_error
  end

  private

  def redirect_to_user_defined_page
    @page = Page.where(uri: params[:path]).first

    if @page.present?
      puts "PAGE: #{@page.inspect}"
      render "pages/show"
    else
      nil
    end
  end

  def raise_error
    raise ActionController::RoutingError, "No route matches [GET] \"/#{params[:path]}\""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinymceTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/main_navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.haml
=form_for page do |f|
  = render 'shared/form_errors', model: page
  %p.form-group
    =f.label :title
    =f.text_field :title
  %p.form-group
    =f.label :uri, 'Page location', placeholder: '/my_new_page'
    =f.text_field :uri
  %p.form-group
    =f.label :in_menu, 'Shown in menu?'
    =f.check_box :in_menu
  %p.form-group
    =f.label :body
    =f.text_area :body, class: 'tinymce', rows: 20, cols: 80
    =tinymce
  %p.form-group
    =f.submit page.id.present? ? 'Update' : 'Save'

app/views/pages/edit.html.haml
=link_to 'Back', page_path(@page)
=link_to 'DELETE', page_path(@page), method: :delete

%h1 Edit Page

= render 'form', page: @page

app/views/pages/index.html.haml
%h1 Page Admin
=link_to 'Create new page', new_page_path

%h2 Current Pages
%ul
  - @pages.each do |page|
    %li=link_to page.title, page_path(page)

app/views/pages/new.html.haml
=link_to 'Back', pages_path
%h1 New Page

= render 'form', page: @page

app/views/pages/show.html.haml
=link_to 'Back', pages_path
=link_to 'Edit', edit_page_path(@page)
%h1=@page.title

=raw @page.body

app/views/shared/_form_errors.html.haml
- if model.errors.any?
  .form_errors
    %h2="#{pluralize(model.errors.count, 'error')} prevented this record from being saved:"
    %ul
      - model.errors.full_messages.each do |message|
        %li=message

app/views/shared/_main_navigation.html.haml
%nav
  %ul
    - Page.all_in_menu.ordered_by_title.each do |page|
      %li
        %a{href: "/#{page.uri}"}=page.uri.gsub('-', ' ').humanize